services:
  front:
    image: node:22
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=development
    working_dir: /usr/app
    restart: always
    command: bash -c "npm install && npm run build && npm run dev"
    ports:
      - 5173:5173
